// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared.Infrastructure.Persistence;

#nullable disable

namespace Shared.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410213904_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Domain.Entities.Allergy", b =>
                {
                    b.Property<int>("AllergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllergyId"));

                    b.Property<int?>("CaseScenarioId")
                        .HasColumnType("int");

                    b.Property<string>("Reaction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Substance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AllergyId");

                    b.HasIndex("CaseScenarioId");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("Shared.Domain.Entities.CaseGoal", b =>
                {
                    b.Property<int>("CaseGoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseGoalId"));

                    b.Property<int?>("CaseScenarioId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeLimitSeconds")
                        .HasColumnType("int");

                    b.HasKey("CaseGoalId");

                    b.HasIndex("CaseScenarioId");

                    b.ToTable("CaseGoals");
                });

            modelBuilder.Entity("Shared.Domain.Entities.CaseScenario", b =>
                {
                    b.Property<int>("CaseScenarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseScenarioId"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InitialVitalsVitalSignsId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaseScenarioId");

                    b.HasIndex("InitialVitalsVitalSignsId");

                    b.HasIndex("PatientId");

                    b.ToTable("CaseScenarios");
                });

            modelBuilder.Entity("Shared.Domain.Entities.DebriefReport", b =>
                {
                    b.Property<int>("DebriefReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DebriefReportId"));

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SimulationSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DebriefReportId");

                    b.ToTable("DebriefReports");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Intervention", b =>
                {
                    b.Property<int>("InterventionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterventionId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Route")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SimulationSessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterventionId");

                    b.HasIndex("SimulationSessionId");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("Shared.Domain.Entities.MedicationOrder", b =>
                {
                    b.Property<int>("MedicationOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicationOrderId"));

                    b.Property<int?>("CaseScenarioId")
                        .HasColumnType("int");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicationOrderId");

                    b.HasIndex("CaseScenarioId");

                    b.ToTable("MedicationOrders");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CurrentDiagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Shared.Domain.Entities.SimulationSession", b =>
                {
                    b.Property<int>("SimulationSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SimulationSessionId"));

                    b.Property<int>("CaseScenarioId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SimulationSessionId");

                    b.HasIndex("CaseScenarioId");

                    b.ToTable("SimulationSessions");
                });

            modelBuilder.Entity("Shared.Domain.Entities.TeacherObservation", b =>
                {
                    b.Property<int>("TeacherObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherObservationId"));

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SimulationSessionId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("TeacherObservationId");

                    b.HasIndex("SimulationSessionId");

                    b.ToTable("TeacherObservations");
                });

            modelBuilder.Entity("Shared.Domain.Entities.TimelineEvent", b =>
                {
                    b.Property<int>("TimelineEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimelineEventId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SimulationSessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("TimelineEventId");

                    b.HasIndex("SimulationSessionId");

                    b.ToTable("TimelineEvents");
                });

            modelBuilder.Entity("Shared.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shared.Domain.Entities.VitalSigns", b =>
                {
                    b.Property<int>("VitalSignsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VitalSignsId"));

                    b.Property<int>("DiastolicBp")
                        .HasColumnType("int");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int");

                    b.Property<int>("OxygenSaturation")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RespiratoryRate")
                        .HasColumnType("int");

                    b.Property<int>("SystolicBp")
                        .HasColumnType("int");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("float");

                    b.HasKey("VitalSignsId");

                    b.ToTable("VitalSigns");
                });

            modelBuilder.Entity("Shared.Domain.Entities.VitalSignsRecord", b =>
                {
                    b.Property<int>("VitalSignsRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VitalSignsRecordId"));

                    b.Property<int>("DiastolicBp")
                        .HasColumnType("int");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int");

                    b.Property<int>("OxygenSaturation")
                        .HasColumnType("int");

                    b.Property<int>("RespiratoryRate")
                        .HasColumnType("int");

                    b.Property<int>("SimulationSessionId")
                        .HasColumnType("int");

                    b.Property<int>("SystolicBp")
                        .HasColumnType("int");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("VitalSignsRecordId");

                    b.HasIndex("SimulationSessionId");

                    b.ToTable("VitalSignRecords");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Allergy", b =>
                {
                    b.HasOne("Shared.Domain.Entities.CaseScenario", null)
                        .WithMany("Allergies")
                        .HasForeignKey("CaseScenarioId");
                });

            modelBuilder.Entity("Shared.Domain.Entities.CaseGoal", b =>
                {
                    b.HasOne("Shared.Domain.Entities.CaseScenario", null)
                        .WithMany("Goals")
                        .HasForeignKey("CaseScenarioId");
                });

            modelBuilder.Entity("Shared.Domain.Entities.CaseScenario", b =>
                {
                    b.HasOne("Shared.Domain.Entities.VitalSigns", "InitialVitals")
                        .WithMany()
                        .HasForeignKey("InitialVitalsVitalSignsId");

                    b.HasOne("Shared.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId");

                    b.Navigation("InitialVitals");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Intervention", b =>
                {
                    b.HasOne("Shared.Domain.Entities.SimulationSession", null)
                        .WithMany("Interventions")
                        .HasForeignKey("SimulationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Domain.Entities.MedicationOrder", b =>
                {
                    b.HasOne("Shared.Domain.Entities.CaseScenario", null)
                        .WithMany("Medications")
                        .HasForeignKey("CaseScenarioId");
                });

            modelBuilder.Entity("Shared.Domain.Entities.SimulationSession", b =>
                {
                    b.HasOne("Shared.Domain.Entities.CaseScenario", "CaseScenario")
                        .WithMany()
                        .HasForeignKey("CaseScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseScenario");
                });

            modelBuilder.Entity("Shared.Domain.Entities.TeacherObservation", b =>
                {
                    b.HasOne("Shared.Domain.Entities.SimulationSession", null)
                        .WithMany("Observations")
                        .HasForeignKey("SimulationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Domain.Entities.TimelineEvent", b =>
                {
                    b.HasOne("Shared.Domain.Entities.SimulationSession", null)
                        .WithMany("TimelineEvents")
                        .HasForeignKey("SimulationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Domain.Entities.VitalSignsRecord", b =>
                {
                    b.HasOne("Shared.Domain.Entities.SimulationSession", null)
                        .WithMany("VitalHistory")
                        .HasForeignKey("SimulationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Domain.Entities.CaseScenario", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("Goals");

                    b.Navigation("Medications");
                });

            modelBuilder.Entity("Shared.Domain.Entities.SimulationSession", b =>
                {
                    b.Navigation("Interventions");

                    b.Navigation("Observations");

                    b.Navigation("TimelineEvents");

                    b.Navigation("VitalHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
